# Generated by Django 5.2.3 on 2025-07-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_bio_user_followers_count_user_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
    ]
